#g++ -o ${BIN}/nhop-neighb ${SRC}/nhop-neighb.cc
#g++ -std=gnu++0x -o ${BIN}/nhop-hood ${SRC}/nhop-hood.cc
BIN=bin
SRC=src
all:
	g++ -o ${BIN}/nhop-bfs ${SRC}/nhop-bfs.cc
	g++ -g -std=c++0x -o ${BIN}/nhop-hood ${SRC}/nhop-hood.cc
	g++ -o ${BIN}/conn_components ${SRC}/conn_components.cc
	g++ -o ${BIN}/convert_to_graphviz ${SRC}/convert_to_graphviz.cc 
